class SalesFieldsMap:
    @staticmethod
    def src_map() -> dict:
        return {
            'Parameters.Начало периода': 'period',
            'Соглашение.Менеджер.Подразделение': 'channel',
            'Соглашение.Подразделение (WA)': 'channel_wa',
            'Соглашение.Менеджер': 'manager',
            'Артикул': 'ean',
            'Номенклатура': 'name',
            'Характеристика': 'ic',
            'Номер проекта': 'opp_num',
            'Заказ.Номер проекта': 'ord_opp_num',
            'Организация': 'sales_org',
            'Клиент': 'customer',
            'Код клиента': 'customer_id',
            'Соглашение': 'agreement',
            'Соглашение.Контрагент.Страна регистрации': 'country',
            'Валюта': 'currency',
            'Заказ': 'order_info',
            'Заказ.Номер по данным клиента': 'order_from_customer',
            'Заказ.Number': 'order_id',
            'Заказ.Date': 'order_date',
            'Дата отгрузки': 'shipment_date',
            'Проект': 'opp_num_header',
            'Проект.Number': 'opp_id',
            'Проект.Название проекта': 'opp_name',
            'Проект.Date': 'opp_date',
            'Проект.Номер в системе партнера': 'opp_partner_id',
            'Проект.Номер (старый)': 'opp_id_old',
            'Коммерческое предложение': 'offer',
            'Коммерческое предложение.Date': 'offer_date',
            'Коммерческое предложение.Number': 'offer_id',
            'Менеджер': 'responsible',
            'Номенклатура.Группа.Группа.Группа.Группа': 'bu',
            'Номенклатура.Группа.Группа.Группа': 'bs',
            'Номенклатура.Группа.Группа': 'ag_key',
            'Номенклатура.Группа': 'aug_key',
            'Характеристика.(WA) Проект IC': 'project_ic',
            'Количество Turnover': 'pcs',
            'Сумма Turnover': 'niv',
        }

    @staticmethod
    def dest_columns() -> list:
        return [
            'period',
            'channel',
            'channel_wa',
            'manager',
            'ean',
            'name',
            'ic',
            'opp_num',
            'ord_opp_num',
            'sales_org',
            'customer',
            'customer_id',
            'agreement',
            'country',
            'currency',
            'order_info',
            'order_from_customer',
            'order_id',
            'order_date',
            'shipment_date',
            'opp_num_header',
            'opp_id',
            'opp_name',
            'opp_date',
            'opp_partner_id',
            'opp_id_old',
            'offer',
            'offer_date',
            'offer_id',
            'responsible',
            'bu',
            'bs',
            'ag_key',
            'aug_key',
            'project_ic',
            'pcs',
            'niv',
        ]

